=encoding utf8

=head1 NAME

Etcd3

=head1 VERSION

Version 0.001

=head1 SYNOPSIS

    Etcd3->new({ host => 'my-etcd.com', port => 4001, user => 'etcd-user' pass => 'P@$$' });

    # put key
    $etcd->put({ key =>'foo1', value => 'bar' });

    # get single key
    $etcd->range({ key =>'test0' });

    # get range of keys
    $etcd->range({ key =>'test0', range_end => 'test100' });

=head1 DESCRIPTION

Perl access to Etcd v3 API.

=head2 host

=head2 port

=head2 user

=head2 password

=head2 ssl

=head2 auth

=head2 api_prefix

base enpoint for api call, refurs to api version.

=head2 headers

returns proper headers for api call.

=head2 range

returns a Etcd3::Range object via Type magic.

$etcd->range({ key =>'test0', range_end => 'test100', serializable => 1 })

=head2 put

returns a Etcd3::Put object via Type magic.

=head2 api_root

=head2 api_path

=head2 actions

outputa aoh defining action class results

=head2

Initialize configuration checks to see it etcd is installed locally.

=head1 AUTHOR

Sam Batschelet, <sbatschelet at mac.com>

=head1 ACKNOWLEDGEMENTS

The L<etcd> developers and community.

=head1 CAVEATS

The L<etcd> v3 API is in heavy development and can change at anytime please see
https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md
for latest details.


=head1 LICENSE AND COPYRIGHT

Copyright 2016 Sam Batschelet (hexfusion).

This program is free software; you can redistribute it and/or modify it
under the terms of either: the GNU General Public License as published
by the Free Software Foundation; or the Artistic License.

See http://dev.perl.org/licenses/ for more information.

